services:
  db:
    image: postgres:16
    container_name: db
    restart: always
    volumes:
      - ~/.pg.pg_data/app:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    build:
      context: .
    container_name: app
    image: app
    restart: always
    entrypoint: /app/start.sh
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${ALLOWED_HOST}
      - LETSENCRYPT_HOST=${ALLOWED_HOST}
      - DEFAULT_HOST=${ALLOWED_HOST}

  nginx:
    build:
      context: ./nginx/
    container_name: nginx
    restart: always
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"

  acme_companion:
    image: nginxproxy/acme-companion
    container_name: acme
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
      - certs:/etc/nginx/certs:rw

volumes:
  certs:
  vhost:
  html:
  acme: